<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-04-20 10:36:59
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-04-20 11:51:18
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-04-20 13:57:48
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-05-08 18:18:36
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-05-09 09:31:33
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-05-16 09:56:34
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-05-31 09:06:13
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-05-31 09:09:27
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-06-12 11:05:20
*/
?>
<?php  exit();
/*
Page: /dedegls/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2017-06-16 09:14:42
*/
?>
